stages:
   - build
   - deploy
   - deploy-digitalocean

deploy-heroku-staging:
  stage: deploy
  image: ruby:2.6
  before_script:
    - gem install dpl --version 1.10.15
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY_STAGING
    - export HEROKU_API_KEY=$HEROKU_API_KEY_STAGING
    - heroku run --app $HEROKU_APP_NAME_STAGING migrate
  environment:
    name: staging
    url: $HEROKU_APP_HOST_STAGING
  only:
    - staging

maven-build:
  image: maven:latest
  stage: build
  script: "mvn clean install -Dmaven.test.skip=true"
  artifacts:
    paths:
      - target/*.jar
  only:
    - adimas

deploy-digitalocean:
  stage: deploy-digitalocean
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - apk add --no-cache bash
    - mkdir -p ~/.ssh
    - echo "$DIGITALOCEAN_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts

    - scp -o StrictHostKeyChecking=no -r ./target root@$DIGITALOCEAN_IP:/deploy
#    - scp -i $DIGITALOCEAN_PRIVATE_KEY target/*.jar root@157.245.63.146:/deploy
  only:
    - adimas